=== trungdong/prov/src/prov/tests/schemas/prov-json.schema.json
{
    "id": "http://provenance.ecs.soton.ac.uk/prov-json/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Schema for a PROV-JSON document",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "prefix": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z0-9_\\-]+$": {
                    "type": "string",
                    "format": "uri"
                }
            }
        },
        "entity": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/entity"
            }
        },
        "activity": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/activity"
            }
        },
        "agent": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/agent"
            }
        },
        "wasGeneratedBy": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/generation"
            }
        },
        "used": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/usage"
            }
        },
        "wasInformedBy": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/communication"
            }
        },
        "wasStartedBy": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/start"
            }
        },
        "wasEndedby": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/end"
            }
        },
        "wasInvalidatedBy": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/invalidation"
            }
        },
        "wasDerivedFrom": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/derivation"
            }
        },
        "wasAttributedTo": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/attribution"
            }
        },
        "wasAssociatedWith": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/association"
            }
        },
        "actedOnBehalfOf": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/delegation"
            }
        },
        "wasInfluencedBy": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/influence"
            }
        },
        "specializationOf": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/specialization"
            }
        },
        "alternateOf": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/alternate"
            }
        },
        "hadMember": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/membership"
            }
        },
        "bundle": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/bundle"
            }
        }
    },
    "definitions": {
        "typedLiteral": {
            "title": "PROV-JSON Typed Literal",
            "type": "object",
            "properties": {
                "$": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "format": "uri"
                },
                "lang": {
                    "type": "string"
                }
            },
            "required": [
                "$"
            ],
            "additionalProperties": false
        },
        "stringLiteral": {
            "type": "string"
        },
        "numberLiteral": {
            "type": "number"
        },
        "booleanLiteral": {
            "type": "boolean"
        },
        "literalArray": {
            "type": "array",
            "minItems": 1,
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/stringLiteral"
                    },
                    {
                        "$ref": "#/definitions/numberLiteral"
                    },
                    {
                        "$ref": "#/definitions/booleanLiteral"
                    },
                    {
                        "$ref": "#/definitions/typedLiteral"
                    }
                ]
            }
        },
        "attributeValues": {
            "anyOf": [
                {
                    "$ref": "#/definitions/stringLiteral"
                },
                {
                    "$ref": "#/definitions/numberLiteral"
                },
                {
                    "$ref": "#/definitions/booleanLiteral"
                },
                {
                    "$ref": "#/definitions/typedLiteral"
                },
                {
                    "$ref": "#/definitions/literalArray"
                }
            ]
        },
        "entity": {
            "type": "object",
            "title": "entity",
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "agent": {
            "$ref": "#/definitions/entity"
        },
        "activity": {
            "type": "object",
            "title": "activity",
            "prov:startTime": {
                "type": "string",
                "format": "date-time"
            },
            "prov:endTime": {
                "type": "string",
                "format": "date-time"
            },
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "generation": {
            "type": "object",
            "title": "generation/usage",
            "properties": {
                "prov:entity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:activity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:time": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "prov:entity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "usage": {
            "$ref": "#/definitions/generation"
        },
        "communication": {
            "type": "object",
            "title": "communication",
            "properties": {
                "prov:informant": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:informed": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:informant",
                "prov:informed"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "start": {
            "type": "object",
            "title": "start/end",
            "properties": {
                "prov:activity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:time": {
                    "type": "string",
                    "format": "date-time"
                },
                "prov:trigger": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:activity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "end": {
            "$ref": "#/definitions/start"
        },
        "invalidation": {
            "type": "object",
            "title": "invalidation",
            "properties": {
                "prov:entity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:time": {
                    "type": "string",
                    "format": "date-time"
                },
                "prov:activity": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:entity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "derivation": {
            "type": "object",
            "title": "derivation",
            "properties": {
                "prov:generatedEntity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:usedEntity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:activity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:generation": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:usage": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:generatedEntity",
                "prov:usedEntity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "attribution": {
            "type": "object",
            "title": "attribution",
            "properties": {
                "prov:entity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:agent": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:entity",
                "prov:agent"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "association": {
            "type": "object",
            "title": "association",
            "properties": {
                "prov:activity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:agent": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:plan": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:activity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "delegation": {
            "type": "object",
            "title": "delegation",
            "properties": {
                "prov:delegate": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:responsible": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:activity": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:delegate",
                "prov:responsible"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "influence": {
            "type": "object",
            "title": "",
            "properties": {
                "prov:influencer": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:influencee": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:influencer",
                "prov:influencee"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "specialization": {
            "type": "object",
            "title": "specialization",
            "properties": {
                "prov:generalEntity": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:specificEntity": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:generalEntity",
                "prov:specificEntity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "alternate": {
            "type": "object",
            "title": "alternate",
            "properties": {
                "prov:alternate1": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:alternate2": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:alternate1",
                "prov:alternate2"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "membership": {
            "type": "object",
            "title": "membership",
            "properties": {
                "prov:collection": {
                    "type": "string",
                    "format": "uri"
                },
                "prov:entity": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "prov:collection",
                "prov:entity"
            ],
            "additionalProperties": {
                "$ref": "#/definitions/attributeValues"
            }
        },
        "bundle": {
            "type": "object",
            "title": "bundle",
            "properties": {
                "prefix": {
                    "type": "object",
                    "patternProperties": {
                        "^[a-zA-Z0-9_\\-]+$": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                },
                "entity": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/entity"
                    }
                },
                "activity": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/activity"
                    }
                },
                "agent": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/agent"
                    }
                },
                "wasGeneratedBy": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/generation"
                    }
                },
                "used": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/usage"
                    }
                },
                "wasInformedBy": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/communication"
                    }
                },
                "wasStartedBy": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/start"
                    }
                },
                "wasEndedby": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/end"
                    }
                },
                "wasInvalidatedBy": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/invalidation"
                    }
                },
                "wasDerivedFrom": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/derivation"
                    }
                },
                "wasAttributedTo": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/attribution"
                    }
                },
                "wasAssociatedWith": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/association"
                    }
                },
                "actedOnBehalfOf": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/delegation"
                    }
                },
                "wasInfluencedBy": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/influence"
                    }
                },
                "specializationOf": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/specialization"
                    }
                },
                "alternateOf": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/alternate"
                    }
                },
                "hadMember": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/membership"
                    }
                }
            }
        }
    }
}

=== trungdong/prov/src/prov/tests/fixtures/written-by-3.2.3/w3c-publication-1.json
{"prefix": {"ex": "http://example.org/", "w3": "http://www.w3.org/", "tr": "http://www.w3.org/TR/2011/", "process": "http://www.w3.org/2005/10/Process-20051014/tr.html#", "email": "https://lists.w3.org/Archives/Member/w3c-archive/", "chairs": "https://lists.w3.org/Archives/Member/chairs/", "trans": "http://www.w3.org/2005/08/01-transitions.html#", "rec54": "http://www.w3.org/2001/02pd/rec54#"}, "entity": {"tr:WD-prov-dm-20111018": {"prov:type": "rec54:WD"}, "tr:WD-prov-dm-20111215": {"prov:type": "rec54:WD"}, "process:rec-advance": {"prov:type": {"$": "prov:Plan", "type": "xsd:QName"}}, "chairs:2011OctDec/0004": {"prov:type": "trans:transreq"}, "email:2011Oct/0141": {"prov:type": "trans:pubreq"}, "email:2011Dec/0111": {"prov:type": "trans:pubreq"}}, "wasDerivedFrom": {"_:id1": {"prov:generatedEntity": "tr:WD-prov-dm-20111215", "prov:usedEntity": "tr:WD-prov-dm-20111018"}}, "activity": {"ex:act1": {"prov:type": "publish"}, "ex:act2": {"prov:type": "publish"}}, "wasGeneratedBy": {"_:id2": {"prov:entity": "tr:WD-prov-dm-20111018", "prov:activity": "ex:act1"}, "_:id3": {"prov:entity": "tr:WD-prov-dm-20111215", "prov:activity": "ex:act2"}}, "used": {"_:id4": {"prov:activity": "ex:act1", "prov:entity": "chairs:2011OctDec/0004"}, "_:id5": {"prov:activity": "ex:act1", "prov:entity": "email:2011Oct/0141"}, "_:id6": {"prov:activity": "ex:act2", "prov:entity": "email:2011Dec/0111"}}, "agent": {"w3:Consortium": {"prov:type": {"$": "prov:Organization", "type": "xsd:QName"}}}, "wasAssociatedWith": {"_:id7": {"prov:activity": "ex:act1", "prov:agent": "w3:Consortium", "prov:plan": "process:rec-advance"}, "_:id8": {"prov:activity": "ex:act2", "prov:agent": "w3:Consortium", "prov:plan": "process:rec-advance"}}}

=== trungdong/prov/src/prov/tests/fixtures/written-by-3.2.3/w3c-publication-2.json
{"prefix": {"hg": "http://dvcs.w3.org/hg/prov/raw-file/9628aaff6e20/model/releases/WD-prov-dm-20111215/", "w3": "http://www.w3.org/TR/2011/", "ex": "http://example.org/", "rec": "http://example.org/record"}, "entity": {"hg:Overview.html": {"prov:type": "file in hg"}, "w3:WD-prov-dm-20111215": {"prov:type": "html4"}, "ex:req3": {"prov:type": {"$": "http://www.w3.org/2005/08/01-transitions.html#pubreq", "type": "xsd:anyURI"}}}, "activity": {"ex:rcp": {"prov:type": "copy directory"}}, "wasGeneratedBy": {"rec:g": {"prov:entity": "w3:WD-prov-dm-20111215", "prov:activity": "ex:rcp"}}, "used": {"rec:u": {"prov:activity": "ex:rcp", "prov:entity": "hg:Overview.html"}, "_:id1": {"prov:activity": "ex:rcp", "prov:entity": "ex:req3"}}, "wasDerivedFrom": {"_:id2": {"prov:generatedEntity": "w3:WD-prov-dm-20111215", "prov:usedEntity": "hg:Overview.html", "prov:activity": "ex:rcp", "prov:generation": "rec:g", "prov:usage": "rec:u"}}, "agent": {"ex:webmaster": {"prov:type": {"$": "prov:Person", "type": "xsd:QName"}}}, "wasAssociatedWith": {"_:id3": {"prov:activity": "ex:rcp", "prov:agent": "ex:webmaster"}}}

=== trungdong/prov/src/prov/tests/fixtures/written-by-3.2.3/bundle2.json
{"prefix": {"ex": "http://www.example.com/", "alice": "http://example.org/alice/", "bob": "http://example.org/bob/"}, "entity": {"bob:bundle4": {"prov:type": {"$": "prov:Bundle", "type": "xsd:QName"}}, "alice:bundle5": {"prov:type": {"$": "prov:Bundle", "type": "xsd:QName"}}}, "wasGeneratedBy": {"_:id1": {"prov:entity": "bob:bundle4", "prov:time": "2012-05-24T10:30:00"}, "_:id3": {"prov:entity": "alice:bundle5", "prov:time": "2012-05-25T11:15:00"}}, "agent": {"ex:Bob": {}, "ex:Alice": {}}, "wasAttributedTo": {"_:id2": {"prov:entity": "bob:bundle4", "prov:agent": "ex:Bob"}, "_:id4": {"prov:entity": "alice:bundle5", "prov:agent": "ex:Alice"}}, "bundle": {"bob:bundle4": {"entity": {"ex:report1": {"prov:type": "report", "ex:version": {"$": "1", "type": "xsd:int"}}}, "wasGeneratedBy": {"_:id1": {"prov:entity": "ex:report1", "prov:time": "2012-05-24T10:00:01"}}}, "alice:bundle5": {"entity": {"ex:report1bis": {}, "ex:report2": {"prov:type": "report", "ex:version": {"$": "2", "type": "xsd:int"}}}, "mentionOf": {"_:id1": {"prov:specificEntity": "ex:report1bis", "prov:generalEntity": "ex:report1", "prov:bundle": "bob:bundle4"}}, "wasGeneratedBy": {"_:id2": {"prov:entity": "ex:report2", "prov:time": "2012-05-25T11:00:01"}}, "wasDerivedFrom": {"_:id3": {"prov:generatedEntity": "ex:report2", "prov:usedEntity": "ex:report1bis"}}}}}

=== trungdong/prov/examples/w3c-publication1.json
{
  "wasAssociatedWith": {
    "_:wAW1": {
      "prov:activity": "w3:Consortium",
      "prov:agent": "ex:pub1",
      "prov:plan": "pr:rec-advance"
    },
    "_:wAW2": {
      "prov:activity": "w3:Consortium",
      "prov:agent": "ex:pub2",
      "prov:plan": "pr:rec-advance"
    }
  },
  "wasGeneratedBy": {
    "_:wGB1": {
      "prov:activity": "ex:pub1",
      "prov:entity": "tr:WD-prov-dm-20111018"
    },
    "_:wGB2": {
      "prov:activity": "ex:pub2",
      "prov:entity": "tr:WD-prov-dm-20111215"
    }
  },
  "entity": {
    "pr:rec-advance": {
      "prov:type": [
        "prov:Plan",
        "xsd:QName"
      ]
    },
    "w3:Consortium": {
      "prov:type": "Organization"
    },
    "tr:WD-prov-dm-20111215": {
      "prov:type": [
        "pr:RecsWD",
        "xsd:QName"
      ]
    },
    "ar2:0141": {
      "prov:type": [
        "http://www.w3.org/2005/08/01-transitions.html#pubreq",
        "xsd:anyURI"
      ]
    },
    "ar3:0111": {
      "prov:type": [
        "http://www.w3.org/2005/08/01-transitions.html#pubreq",
        "xsd:anyURI"
      ]
    },
    "tr:WD-prov-dm-20111018": {
      "prov:type": [
        "pr:RecsWD",
        "xsd:QName"
      ]
    },
    "ar1:0004": {
      "prov:type": [
        "http://www.w3.org/2005/08/01-transitions.html#transreq",
        "xsd:anyURI"
      ]
    }
  },
  "prefix": {
    "ar1": "https://lists.w3.org/Archives/Member/chairs/2011OctDec/",
    "ar2": "https://lists.w3.org/Archives/Member/w3c-archive/2011Oct/",
    "ex": "http://example.org/",
    "ar3": "https://lists.w3.org/Archives/Member/w3c-archive/2011Dec/",
    "tr": "http://www.w3.org/TR/2011/",
    "w3": "http://www.w3.org/",
    "pr": "http://www.w3.org/2005/10/Process-20051014/tr.html#"
  },
  "wasDerivedFrom": {
    "_:wDF1": {
      "prov:generatedEntity": "tr:WD-prov-dm-20111215",
      "prov:usedEntity": "tr:WD-prov-dm-20111018"
    }
  },
  "used": {
    "_:u1": {
      "prov:activity": "ex:pub1",
      "prov:entity": "ar1:0004"
    },
    "_:u3": {
      "prov:activity": "ex:pub2",
      "prov:entity": "ar3:0111"
    },
    "_:u2": {
      "prov:activity": "ex:pub1",
      "prov:entity": "ar2:0141"
    }
  },
  "activity": {
    "ex:pub1": {
      "prov:type": "publish"
    },
    "ex:pub2": {
      "prov:type": "publish"
    }
  }
}

=== trungdong/prov/src/prov/tests/fixtures/written-by-3.2.3/primer.json
{"prefix": {"dcterms": "http://purl.org/dc/terms/", "foaf": "http://xmlns.com/foaf/0.1/", "ex": "http://example/"}, "entity": {"ex:article": {"dcterms:title": "Crime rises in cities"}, "ex:articleV1": {}, "ex:articleV2": {}, "ex:dataSet1": {}, "ex:dataSet2": {}, "ex:regionList": {}, "ex:composition": {}, "ex:chart1": {}, "ex:chart2": {}, "ex:blogEntry": {}}, "activity": {"ex:compile": {}, "ex:compile2": {}, "ex:compose": {}, "ex:correct": {"prov:startTime": "2012-03-31T09:21:00", "prov:endTime": "2012-04-01T15:21:00"}, "ex:illustrate": {}}, "used": {"_:id1": {"prov:activity": "ex:compose", "prov:entity": "ex:dataSet1", "prov:role": "ex:dataToCompose"}, "_:id2": {"prov:activity": "ex:compose", "prov:entity": "ex:regionList", "prov:role": "ex:regionsToAggregateBy"}, "_:id4": {"prov:activity": "ex:illustrate", "prov:entity": "ex:composition"}, "_:id12": {"prov:activity": "ex:correct", "prov:entity": "ex:dataSet1"}}, "wasGeneratedBy": {"_:id3": {"prov:entity": "ex:composition", "prov:activity": "ex:compose"}, "_:id5": {"prov:entity": "ex:chart1", "prov:activity": "ex:illustrate"}, "_:id6": {"prov:entity": "ex:chart1", "prov:activity": "ex:compile", "prov:time": "2012-03-02T10:30:00"}, "_:id11": {"prov:entity": "ex:dataSet2", "prov:activity": "ex:correct"}}, "agent": {"ex:derek": {"prov:type": {"$": "prov:Person", "type": "xsd:QName"}, "foaf:givenName": "Derek", "foaf:mbox": "<mailto:derek@example.org>"}, "ex:chartgen": {"prov:type": {"$": "prov:Organization", "type": "xsd:QName"}, "foaf:name": "Chart Generators Inc"}}, "wasAssociatedWith": {"_:id7": {"prov:activity": "ex:compose", "prov:agent": "ex:derek"}, "_:id8": {"prov:activity": "ex:illustrate", "prov:agent": "ex:derek"}}, "actedOnBehalfOf": {"_:id9": {"prov:delegate": "ex:derek", "prov:responsible": "ex:chartgen", "prov:activity": "ex:compose"}}, "wasAttributedTo": {"_:id10": {"prov:entity": "ex:chart1", "prov:agent": "ex:derek"}}, "wasDerivedFrom": {"_:id13": {"prov:generatedEntity": "ex:dataSet2", "prov:usedEntity": "ex:dataSet1", "prov:type": {"$": "prov:Revision", "type": "xsd:QName"}}, "_:id14": {"prov:generatedEntity": "ex:chart2", "prov:usedEntity": "ex:dataSet2"}, "_:id15": {"prov:generatedEntity": "ex:blogEntry", "prov:usedEntity": "ex:article", "prov:type": {"$": "prov:Quotation", "type": "xsd:QName"}}, "_:id17": {"prov:generatedEntity": "ex:articleV1", "prov:usedEntity": "ex:dataSet1"}, "_:id19": {"prov:generatedEntity": "ex:articleV2", "prov:usedEntity": "ex:dataSet2"}}, "specializationOf": {"_:id16": {"prov:specificEntity": "ex:articleV1", "prov:generalEntity": "ex:article"}, "_:id18": {"prov:specificEntity": "ex:articleV2", "prov:generalEntity": "ex:article"}}, "alternateOf": {"_:id20": {"prov:alternate1": "ex:articleV2", "prov:alternate2": "ex:articleV1"}}}
